# Descobrindo a tabuada
n = int (input ('Digite o numero que deseja saber a tabuada completa: '))
a = (n * 0)
b = (n * 1)
c = (n * 2)
d = (n * 3)
e = (n * 4)
f = (n * 5)
g = (n * 6)
h = (n * 7)
i = (n * 8)
j = (n * 9)
k = (n * 10)
print ('A tabuada do {} é: \n  0 = {} \n  1 = {} \n  2 = {} \n  3 = {} \n  4 = {} \n  5 = {} \n  6 = {} \n  7 = {} \n  8 = {} \n  9 = {} \n 10 = {}' .format ( n, a, b, c, d, e, f, g, h, i, j, k))
