nome = input('Digite seu nome completo: ')
print ('Nome com todas as letras maiusculas. ', nome.upper())
print ('Nome com todas as letras minusculas. ',nome.lower())
nome2 = (nome.split())
''.join (nome2)
nome3 = ''.join(nome2)
#print ('Nome sem o uso de espaços. ',nome3)
print ('Numero de letras do seu nome. ',len (nome3))
print ('Numero de letras do seu primeiro nome. ', len (nome2[0]))
